### ISSUE TITLE
Client freezes when opening world map

### ISSUE THREAD

**Issue by azzawoody** [runeliteplusplus/RuneLitePlusPlus#11]
client freezes/crashes everytime I click on the minimap  try and open the floating world map sometimes it will load but very rarely have to close client and restart

**Comment by runeliteplusplus** [comment]
Hello,

You are not the only person who has reported this problem, I personally don't experience it but am aware it exists.

This is definitely a problem related to RuneLite, maybe something based on running a .jar directly, or not building it on your own hardware, but it is not related to our plugins.

This is a question to be asked on the official RuneLite repo.

If you want, you can try disabling our plugins one at a time and seeing if any of them turned off magically fixes this problem, if so please do let me know so I can take a closer look.
