### ISSUE TITLE
Zulrah helper

### ISSUE THREAD

**Issue by supermxn** [runeliteplusplus/RuneLitePlusPlus#12]
I have found the old version of the zulrah helper that has being used on RL before it was deleted. I could be wrong that you are already using it. I can attach it on here, unless you want me to PM it to you externally.

Edit: I will go ahead and attach it.

[zulrah.zip](https://github.com/runeliteplusplus/RuneLitePlusPlus/files/2944630/zulrah.zip)

**Comment by bigmemes420** [comment]
I'd say the current zulrah helper the client has is fine.

**Comment by flewychan** [comment]
will try, thanks

**Comment by runeliteplusplus** [comment]
Hello,

Does this plugin have any features that ours does not? I'll be happy to look at implementing them.

**Comment by supermxn** [comment]
> 
> 
> Hello,
> 
> Does this plugin have any features that ours does not? I'll be happy to look at implementing them.

Well I don't code, but other people on discord has been saying the code is "ugly" and the one runelite coded is better and clean?

**Comment by bigmemes420** [comment]
> > Hello,
> > Does this plugin have any features that ours does not? I'll be happy to look at implementing them.
> 
> Well I don't code, but other people on discord has been saying the code is "ugly" and the one runelite coded is better and clean?

My only complaint would be the Zulrah spawn tiles drawing over the prayers.
