### ISSUE TITLE
Vorkath plugin questions

### ISSUE THREAD

**Issue by kaffeknugen** [runeliteplusplus/RuneLitePlusPlus#13]
Hi. A suggestion for the vorkath plugin is to show where the acid pools are gonna land before they hit the ground so that you can dodge them easier. And also. The timer(s) or numbers abow vorkath makes no sense. I have done 15 kills with the plugin now and it still doesnt make any sense to me. Please explain what they mean.

Thanks =)

**Comment by supermxn** [comment]
Oh yea, thanks for reminding me about where the acid pools will land. Hopefully he'll add that, As for the numbers above his head are the "big" attacks that will come. They can be the zombie spawn, fireball or acid pools.

**Comment by runeliteplusplus** [comment]
Hello,

Thank you for bringing this to my attention. It appears the Vorkath animation's have been slightly changed in some recent update. This caused the plugin to think every 1 attack was actually 2 and caused everything to go out of sync.

I've adjusted the plugin and this is now fixed, have a go with the latest version and let me know if it makes sense now :)

Regarding the acid pool tile highlighting, I'm going to need some help figuring out which RuneLite event can get information on these, it may not be possible at all. If you can provide this I'll happily implement it.

**Comment by kaffeknugen** [comment]
I dont know the java language. But i know one thing. My friend has ALOT of custom plugins that he recieves from a friend of his. And he have a working vorkath plugin that tells you where the acid pools are gonna land. He told me that Runelite hid the game event for vorkath pools. So his friend had to do a something else idk. Workaround it someone. So there is no need to test game events since non of them will work. I can problably help you no further other than that i found some info about vorkath pools. Maybe it's from before the update. Worth a shot.

This is a whole other tipic i change to now.

Do you create all your plugins yourself? Cuz i have been searching around for plugins and come across 2 or 3 really helpful ones that i like alot. Im not the creator of them. Dont know who is.



Maybe you can get this to work

**Comment by kaffeknugen** [comment]
package net.runelite.client.plugins.aoewarnings;

import java.time.Instant;
import net.runelite.api.coords.LocalPoint;

class AoeProjectile
{
	private final Instant startTime;
	private final LocalPoint targetPoint;
	private final AoeProjectileInfo aoeProjectileInfo;

	AoeProjectile(Instant startTime, LocalPoint targetPoint, AoeProjectileInfo aoeProjectileInfo)
	{
		this.startTime = startTime;
		this.targetPoint = targetPoint;
		this.aoeProjectileInfo = aoeProjectileInfo;
	}

	Instant getStartTime()
	{
		return startTime;
	}

	LocalPoint getTargetPoint()
	{
		return targetPoint;
	}

	AoeProjectileInfo getAoeProjectileInfo()
	{
		return aoeProjectileInfo;
	}
}

**Comment by kaffeknugen** [comment]
package net.runelite.client.plugins.aoewarnings;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;
import net.runelite.api.ProjectileID;

public enum AoeProjectileInfo
{
	LIZARDMAN_SHAMAN_AOE(ProjectileID.LIZARDMAN_SHAMAN_AOE, 3000, 3),
	CRAZY_ARCHAEOLOGIST_AOE(ProjectileID.CRAZY_ARCHAEOLOGIST_AOE, 3000, 3),
	ICE_DEMON_RANGED_AOE(ProjectileID.ICE_DEMON_RANGED_AOE, 3000, 3),
	/**
	 * When you don't have pray range on ice demon does an ice barrage
	 */
	ICE_DEMON_ICE_BARRAGE_AOE(ProjectileID.ICE_DEMON_ICE_BARRAGE_AOE, 3000, 3),
	/**
	 * The AOE when vasa first starts
	 */
	VASA_AWAKEN_AOE(ProjectileID.VASA_AWAKEN_AOE, 4500, 3),
	VASA_RANGED_AOE(ProjectileID.VASA_RANGED_AOE, 3000, 3),
	TEKTON_METEOR_AOE(ProjectileID.TEKTON_METEOR_AOE, 4000, 3),

	/**
	 * The AOEs of Vorkath
	 */
	VORKATH_BOMB(ProjectileID.VORKATH_BOMB_AOE, 2400, 3),
	VORKATH_POISON_POOL(ProjectileID.VORKATH_POISON_POOL_AOE, 1800, 1),
	VORKATH_SPAWN(ProjectileID.VORKATH_SPAWN_AOE, 3000, 1), //extra tick because hard to see otherwise
	VORKATH_TICK_FIRE(ProjectileID.VORKATH_TICK_FIRE_AOE, 600, 1),

	/**
	 * the AOEs of Galvek
	 */
	GALVEK_MINE(ProjectileID.GALVEK_MINE, 3600, 3),
	GALVEK_BOMB(ProjectileID.GALVEK_BOMB, 2400, 3),

	/**
	 * the AOE of Vet'ion
	 */
	VETION_LIGHTNING(ProjectileID.VETION_LIGHTNING, 3000, 1),

	/**
	 * the AOE of Chaos Fanatic
	 */
	CHAOS_FANATIC(ProjectileID.CHAOS_FANATIC_AOE, 3000, 1),

	/**
	 * the AOE of the Corporeal Beast
	 */

	CORPOREAL_BEAST(ProjectileID.CORPOREAL_BEAST_AOE, 3000, 1),
	CORPOREAL_BEAST_DARK_CORE(ProjectileID.CORPOREAL_BEAST_DARK_CORE_AOE, 3000, 3),

	/**
	 * the AOEs of The Great Olm
	 * missing ids and length, please help
	 */
	OLM_FALLING_CRYSTAL(ProjectileID.OLM_FALLING_CRYSTAL_AOE, 2400, 3),
	OLM_BURNING(ProjectileID.OLM_BURNING_AOE, 2400, 3),

	/**
	 * the AOE of the Wintertodt snow that falls
	 */
	WINTERTODT_SNOW_FALL(ProjectileID.WINTERTODT_SNOW_FALL_AOE, 4000, 3);


	/**
	 * The id of the projectile to trigger this AoE warning
	 */
	private final int id;

	/**
	 * How long the indicator should last for this AoE warning This might
	 * need to be a bit longer than the projectile actually takes to land as
	 * there is a fade effect on the warning
	 */
	private final Duration lifeTime;

	/**
	 * The size of the splash radius of the AoE warning Ex. Lizardman shaman
	 * AoE is a 3x3, so aoeSize = 3
	 */
	private final int aoeSize;

	private static final Map<Integer, AoeProjectileInfo> map = new HashMap<>();

	static
	{
		for (AoeProjectileInfo aoe : values())
		{
			map.put(aoe.id, aoe);
		}
	}

	AoeProjectileInfo(int id, int lifeTimeMillis, int aoeSize)
	{
		this.id = id;
		this.lifeTime = Duration.ofMillis(lifeTimeMillis);
		this.aoeSize = aoeSize;
	}

	public Duration getLifeTime()
	{
		return lifeTime;
	}

	public int getId()
	{
		return id;
	}

	public int getAoeSize()
	{
		return aoeSize;
	}

	public static AoeProjectileInfo getById(int id)
	{
		return map.get(id);
	}
}

**Comment by kaffeknugen** [comment]
package net.runelite.client.plugins.aoewarnings;

import net.runelite.client.config.Config;
import net.runelite.client.config.ConfigGroup;
import net.runelite.client.config.ConfigItem;

@ConfigGroup("aoewarnings")
public interface AoeWarningConfig extends Config
{
	@ConfigItem(
		keyName = "enabled",
		name = "AoE Warnings Enabled",
		description = "Configures whether or not AoE Projectile Warnings plugin is displayed"
	)
	default boolean enabled()
	{
		return true;
	}

	@ConfigItem(
		keyName = "lizardmanaoe",
		name = "Lizardman Shamans",
		description = "Configures whether or not AoE Projectile Warnings for Lizardman Shamans is displayed"
	)
	default boolean isShamansEnabled()
	{
		return true;
	}

	@ConfigItem(
		keyName = "archaeologistaoe",
		name = "Crazy Archaeologist",
		description = "Configures whether or not AoE Projectile Warnings for Archaeologist is displayed"
	)
	default boolean isArchaeologistEnabled()
	{
		return true;
	}

	@ConfigItem(
		keyName = "icedemon",
		name = "Ice Demon",
		description = "Configures whether or not AoE Projectile Warnings for Ice Demon is displayed"
	)
	default boolean isIceDemonEnabled()
	{
		return true;
	}

	@ConfigItem(
		keyName = "vasa",
		name = "Vasa",
		description = "Configures whether or not AoE Projectile Warnings for Vasa is displayed"
	)
	default boolean isVasaEnabled()
	{
		return true;
	}

	@ConfigItem(
		keyName = "tekton",
		name = "Tekton",
		description = "Configures whether or not AoE Projectile Warnings for Tekton is displayed"
	)
	default boolean isTektonEnabled()
	{
		return true;
	}

	@ConfigItem(
		keyName = "vorkath",
		name = "Vorkath",
		description = "Configures whether or not AoE Projectile Warnings for Vorkath are displayed"
	)
	default boolean isVorkathEnabled()
	{
		return true;
	}

	@ConfigItem(
		keyName = "galvek",
		name = "Galvek",
		description = "Configures whether or not AoE Projectile Warnings for Galvek are displayed"
	)
	default boolean isGalvekEnabled()
	{
		return true;
	}

	@ConfigItem(
		keyName = "vetion",
		name = "Vet'ion",
		description = "Configures whether or not AoE Projectile Warnings for Vet'ion are displayed"
	)
	default boolean isVetionEnabled()
	{
		return true;
	}

	@ConfigItem(
		keyName = "chaosfanatic",
		name = "Chaos Fanatic",
		description = "Configures whether or not AoE Projectile Warnings for Chaos Fanatic are displayed"
	)
	default boolean isChaosFanaticEnabled()
	{
		return true;
	}

	@ConfigItem(
		keyName = "olm",
		name = "Great Olm",
		description = "Configures whether or not AoE Projectile Warnings for The Great Olm are displayed"
	)
	default boolean isOlmEnabled()
	{
		return true;
	}

	@ConfigItem(
		keyName = "corp",
		name = "Corporeal Beast",
		description = "Configures whether or not AoE Projectile Warnings for the Corporeal Beast are displayed"
	)
	default boolean isCorpEnabled()
	{
		return true;
	}

	@ConfigItem(
		keyName = "wintertodt",
		name = "Wintertodt Snow Fall",
		description = "Configures whether or not AOE Projectile Warnings for the Wintertodt snow fall are displayed"
	)
	default boolean isWintertodtEnabled()
	{
		return true;
	}

	@ConfigItem(
		keyName = "outline",
		name = "Display Outline",
		description = "Configures whether or not AoE Projectile Warnings have an outline"
	)
	default boolean isOutlineEnabled()
	{
		return true;
	}
}

**Comment by kaffeknugen** [comment]
package net.runelite.client.plugins.aoewarnings;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Polygon;
import java.time.Instant;
import java.util.Iterator;
import javax.annotation.Nullable;
import javax.inject.Inject;
import net.runelite.api.Client;
import net.runelite.api.Perspective;
import net.runelite.client.ui.overlay.Overlay;
import net.runelite.client.ui.overlay.OverlayLayer;
import net.runelite.client.ui.overlay.OverlayPosition;
import net.runelite.client.ui.overlay.OverlayUtil;

public class AoeWarningOverlay extends Overlay
{
	private static final int FILL_START_ALPHA = 25;
	private static final int OUTLINE_START_ALPHA = 255;

	private final Client client;
	private final AoeWarningPlugin plugin;
	private final AoeWarningConfig config;

	@Inject
	public AoeWarningOverlay(@Nullable Client client, AoeWarningPlugin plugin, AoeWarningConfig config)
	{
		setPosition(OverlayPosition.DYNAMIC);
		setLayer(OverlayLayer.UNDER_WIDGETS);
		this.client = client;
		this.plugin = plugin;
		this.config = config;
	}

	@Override
	public Dimension render(Graphics2D graphics)
	{
		if (!config.enabled())
			return null;

		for (Iterator<AoeProjectile> it = plugin.getProjectiles().values().iterator(); it.hasNext();)
		{
			AoeProjectile aoeProjectile = it.next();

			if (Instant.now().isAfter(aoeProjectile.getStartTime().plus(aoeProjectile.getAoeProjectileInfo().getLifeTime())))
			{
				it.remove();
				continue;
			}

			Polygon tilePoly = Perspective.getCanvasTileAreaPoly(client, aoeProjectile.getTargetPoint(), aoeProjectile.getAoeProjectileInfo().getAoeSize());

			if (tilePoly == null)
				continue;

			// how far through the projectiles lifetime between 0-1.
			double progress = (System.currentTimeMillis() - aoeProjectile.getStartTime().toEpochMilli()) / (double) aoeProjectile.getAoeProjectileInfo().getLifeTime().toMillis();

			int fillAlpha = (int) ((1 - progress) * FILL_START_ALPHA);//alpha drop off over lifetime
			int outlineAlpha = (int) ((1 - progress) * OUTLINE_START_ALPHA);

			if (fillAlpha < 0)
			{
				fillAlpha = 0;
			}
			if (outlineAlpha < 0)
			{
				outlineAlpha = 0;
			}

			if (fillAlpha > 255)
			{
				fillAlpha = 255;
			}
			if (outlineAlpha > 255)
			{
				outlineAlpha = 255;//Make sure we don't pass in an invalid alpha
			}

			if (config.isOutlineEnabled())
				OverlayUtil.renderPolygon(graphics, tilePoly, new Color(255, 0, 0, outlineAlpha));

			graphics.setColor(new Color(255, 0, 0, fillAlpha));
			graphics.fillPolygon(tilePoly);
		}
		return null;
	}
}

**Comment by kaffeknugen** [comment]
package net.runelite.client.plugins.aoewarnings;

import com.google.inject.Binder;
import com.google.inject.Provides;
import java.time.Instant;
import java.util.HashMap;
import java.util.Map;
import javax.inject.Inject;
import net.runelite.api.Point;
import net.runelite.api.Projectile;
import net.runelite.api.coords.LocalPoint;
import net.runelite.client.config.ConfigManager;
import net.runelite.api.events.ProjectileMoved;
import net.runelite.client.eventbus.Subscribe;
import net.runelite.client.plugins.Plugin;
import net.runelite.client.plugins.PluginDescriptor;
import net.runelite.client.ui.overlay.Overlay;
import net.runelite.client.ui.overlay.OverlayManager;

@PluginDescriptor(
	name = "!AoE warnings"
)
public class AoeWarningPlugin extends Plugin
{
	@Inject
	AoeWarningOverlay overlay;

	@Inject
	AoeWarningConfig config;

	@Inject
	private OverlayManager overlayManager;

	private final Map<Projectile, AoeProjectile> projectiles = new HashMap<>();

	@Override
	public void configure(Binder binder)
	{
		binder.bind(AoeWarningOverlay.class);
	}

	@Provides
	AoeWarningConfig getConfig(ConfigManager configManager)
	{
		return configManager.getConfig(AoeWarningConfig.class);
	}

	public Overlay getOverlay()
	{
		return overlay;
	}

	Map<Projectile, AoeProjectile> getProjectiles()
	{
		return projectiles;
	}

	@Override
	protected void startUp() throws Exception
	{
		overlayManager.add(overlay);
	}

	@Override
	protected void shutDown() throws Exception
	{
		overlayManager.remove(overlay);
	}

	/**
	 * Called when a projectile is set to move towards a point. For
	 * projectiles that target the ground, like AoE projectiles from
	 * Lizardman Shamans, this is only called once
	 *
	 * @param event Projectile moved event
	 */
	@Subscribe
	public void onProjectileMoved(ProjectileMoved event)
	{
		Projectile projectile = event.getProjectile();

		// AoE projectiles do not target anything
		if (projectile.getInteracting() != null)
		{
			return;
		}

		int projectileId = projectile.getId();
		AoeProjectileInfo aoeProjectileInfo = AoeProjectileInfo.getById(projectileId);
		if (aoeProjectileInfo != null && isConfigEnabledForProjectileId(projectileId))
		{
			LocalPoint targetPoint = event.getPosition();
			AoeProjectile aoeProjectile = new AoeProjectile(Instant.now(), targetPoint, aoeProjectileInfo);
			projectiles.put(projectile, aoeProjectile);
		}
	}

	private boolean isConfigEnabledForProjectileId(int projectileId)
	{
		AoeProjectileInfo projectileInfo = AoeProjectileInfo.getById(projectileId);
		if (projectileInfo == null)
		{
			return false;
		}

		switch (projectileInfo)
		{
			case LIZARDMAN_SHAMAN_AOE:
				return config.isShamansEnabled();
			case CRAZY_ARCHAEOLOGIST_AOE:
				return config.isArchaeologistEnabled();
			case ICE_DEMON_RANGED_AOE:
			case ICE_DEMON_ICE_BARRAGE_AOE:
				return config.isIceDemonEnabled();
			case VASA_AWAKEN_AOE:
			case VASA_RANGED_AOE:
				return config.isVasaEnabled();
			case TEKTON_METEOR_AOE:
				return config.isTektonEnabled();
			case VORKATH_BOMB:
			case VORKATH_POISON_POOL:
			case VORKATH_SPAWN:
			case VORKATH_TICK_FIRE:
				return config.isVorkathEnabled();
			case VETION_LIGHTNING:
				return config.isVetionEnabled();
			case CHAOS_FANATIC:
				return config.isChaosFanaticEnabled();
			case GALVEK_BOMB:
			case GALVEK_MINE:
				return config.isGalvekEnabled();
			case OLM_FALLING_CRYSTAL:
			case OLM_BURNING:
				return config.isOlmEnabled();
			case CORPOREAL_BEAST:
			case CORPOREAL_BEAST_DARK_CORE:
				return config.isCorpEnabled();
			case WINTERTODT_SNOW_FALL:
				return config.isWintertodtEnabled();
		}

		return false;
	}
}
