### ISSUE TITLE
AOE warning plugin?

### ISSUE THREAD

**Issue by supermxn** [runeliteplusplus/RuneLitePlusPlus#14]
Hello, I have found the original AOE files that RuneLite have used from the archive. But I was thinking of adding this, as this will help me and others for bossing. I can attach the .java files if needed let me know please. As you know those codes are outdated, I would love to see it on the client. 

EDIT: I know someone posted this, but was thinking if it is being worked on?

**Comment by runeliteplusplus** [comment]
I'm fairly confident RuneLite modified something with the projectile event that makes that plugin obsolete.

If there is a specific boss or situation you'd like a plugin for, let me know, or list everywhere an AoE plugin can benefit from and I can hard code each one.

**Comment by supermxn** [comment]
Here's the AOE .jave files [aoewarnings.zip](https://github.com/runeliteplusplus/RuneLitePlusPlus/files/2964068/aoewarnings.zip)
Crazy Archaeologist, Great Olm, Corporeal Beast, Shaman Lizard and a few others that are from Raids I can not remember. The IDs should be in those .java files.

**Comment by bigmemes420** [comment]
There's 2 current problems with AOE warnings, they never worked for olm bombs (as they aren't proper projectiles/the ids are not in runelite) and projectile.getInteracting has changed for runelite.

**Comment by 13ethan13** [comment]
Something you can do for bombs is just have a range on them (the 5x5 square) and a timer counting them down til they explode.
