### ISSUE TITLE
Freeze timer

### ISSUE THREAD

**Issue by xKylee** [runeliteplusplus/RuneLitePlusPlus#16]
I’ve noticed a few issues with  the freeze timer plugin, 1 may be by design however:

1) the freeze timer itself sits extremely high above the person frozen, is there a way to move it to the persons body like exilent does to make it look cleaner: http://i.imgur.com/tjDIxDa.png

2) when using auto cast the timer does not display, the timer will only display when manually casting.

Also. Would it be possible to implement a TB timer into this too to sit along side the freeze timer?

**Comment by runeliteplusplus** [comment]
I've updated the freeze timers plugin with the following changes:

- Config setting to adjust the info overlays up / down

- Config setting to enable TB timer

Here are the drawbacks of using freezetimers in RuneLite: https://github.com/runeliteplusplus/RuneLitePlusPlus/commit/c384041d60b08219ad8e921cbcb34d61210c59c1

Unlike other client's that have access to graphic / animation ID data, RuneLite does not, so our plugin must work in a very duct taped together fashion that has many drawbacks, but it is still more useful then not having anything at all.

Let me know what you think of these changes and if there is anything else that can be improved.
