### ISSUE TITLE
New plugins

### ISSUE THREAD

**Issue by xKylee** [runeliteplusplus/RuneLitePlusPlus#21]
Is there a way to contact you @runeliteplusplus to discuss some idea’s for new plugins? If not I can write them here

**Comment by old-kyle-escabar** [comment]
@runeliteplusplus I have  been on my own maintaining this repo when runelite updates within hours either with new versions or new plugins. If it is something you would like me to submit pull requests for I would be happy to.

**Comment by kyle-escobar** [comment]
@Kyleeld Please write the names here. As stated before I have been personally maintaining this for myself as I use zulrah. I will add them in and update a new issue with my requests.

**Comment by old-kyle-escabar** [comment]
I have forked the code here: https://github.com/kyle-escobar/RuneLitePlusPlus/releases/tag/1.5.22 
@Kyleeld If you would like you can add the names and I will add them to my fork

**Comment by Enza-Denino** [comment]
@Kyleeld 

@kyle-escobar are you still maintaining the fork?

it looks like the original maintainer doesn't have enough time to keep the plugins up to date or pull in new features

https://github.com/runelite-extended/runelite looks like it is more regularly maintained and updated, maybe it would be easier to focus efforts over there
