### ISSUE TITLE
Zulrah breaks after a few updates/compiles

### ISSUE THREAD

**Issue by formatme** [runeliteplusplus/RuneLitePlusPlus#4]
Zulrah breaks after a few updates/compiles,
it was working fine not it doesn't. nothing works as if the plugin was off and no errors.
a old build of runelite with the plugin works fine but with newer builds it no longer works.

**Comment by formatme** [comment]
noticed the plugin using import com.google.common.eventbus.Subscribe;
changed it to import net.runelite.client.eventbus.Subscribe;

gonna see if it works now

**Comment by formatme** [comment]
works, that change will fix it

**Comment by runeliteplusplus** [comment]
Updated.
