### ISSUE TITLE
Plugin request :)

### ISSUE THREAD

**Issue by Druxlolz** [runeliteplusplus/RuneLitePlusPlus#6]
Hello RuneLitePlusPlus.

I know this may be asking for much and i'm sorry if it offends you.
But i just wanted to ask if it's possible for you to make / share a hydra attack counter plugin? :)

Anyway have a nice day! 👍

**Comment by runeliteplusplus** [comment]
Unfortunately I'd have no way of testing this as I don't have access to hydra.

If you have any plugin requests, don't be afraid to ask, I am open to suggestions. I was considering something for vorkath, but honestly a plugin wouldn't be much benefit there. Inferno is another possibility, but that would be a lot of work and has the risk of RuneLite patching it as they did freeze timers so I'm hesitant to make it.

There is a BIG opportunity for cross-client communications, to make features like showing where team members are on minimap, inventories, loot piles, etc, however this requires external network communication which would expose the IP of RL++ users. I was thinking of making this an optional feature in some plugins where you input the IP and port of your private server along with an open source stub to handle the communications, so clans would just need a single cheap VPS for this functionality.

Anyways these are just a few of my ideas on where this client can go, let me know what you think as I value user feedback greatly.

**Comment by bigmemes420** [comment]
> Unfortunately I'd have no way of testing this as I don't have access to hydra.
> 
> If you have any plugin requests, don't be afraid to ask, I am open to suggestions. I was considering something for vorkath, but honestly a plugin wouldn't be much benefit there. Inferno is another possibility, but that would be a lot of work and has the risk of RuneLite patching it as they did freeze timers so I'm hesitant to make it.
> 
> There is a BIG opportunity for cross-client communications, to make features like showing where team members are on minimap, inventories, loot piles, etc, however this requires external network communication which would expose the IP of RL++ users. I was thinking of making this an optional feature in some plugins where you input the IP and port of your private server along with an open source stub to handle the communications, so clans would just need a single cheap VPS for this functionality.
> 
> Anyways these are just a few of my ideas on where this client can go, let me know what you think as I value user feedback greatly.

If you post what you need from hydra I would be willing to gather it for you and test it. (Animation IDs etc).
If you'd like to talk to me directly send me your discord.

**Comment by ghost** [comment]
Anyone should have access to the alchemical hydra on unrestricted/tournament worlds as long as they have a members account.

**Comment by ghost** [comment]
Vorkath alternates between 2 special attacks every 6 standard attacks so a similar counter could be useful to anticipate when and which its next special attack will be.

**Comment by bigmemes420** [comment]
> Anyone should have access to the alchemical hydra on unrestricted/tournament worlds as long as they have a members account.

Yea but having to go and get a new hydra task every time you recompile the client to test the plugin might be quite the annoyance so just having it ready to go on the normal servers would ease that.

**Comment by ghost** [comment]
This plugin could be tested on normal hydras first which doesn't require any task.

**Comment by bigmemes420** [comment]
Yea but those hydras can be effected by other players.

**Comment by ghost** [comment]
For a "hydra plugin" I assumed it will also have support for the normal hydras. It uses the 1-2-3 attack pattern so how is it effected by other players?

**Comment by bigmemes420** [comment]
They could do 2 range attacks, and you wouldn't have them loaded so you wouldn't be able to see those attacks therefore you would think there's 3 attacks when there is only 1 as other players can cause them to use their attacks.

**Comment by ghost** [comment]
It should be able to keep track after the first switch similar to the demonic gorilla plugin.

**Comment by runeliteplusplus** [comment]
Thank you all for the feedback.

I've just published a Vorkath plugin that I must say works quite well.

As for Hydra, I've made a plugin that tells you what to pray against regular hydra's, but not the hydra boss.

For some reason I am not able to read any data regarding Alchemical hydra's animation / graphic ID's.

I would like someone to confirm if it is possible to read Alchemical hydra data with the current RuneLite version, it is possible they have already restricted this to prevent plugins here.

If it is not possible, I'll just publish the regular hydra plugin as I'm sure it will still be of use, but it's a shame the boss is filtered.

Some advice to whomever wants to help: You can repeatedly get a new assignment from Konar on the tourney world, so you can just spam assignment till you get hydra's.

**Comment by ghost** [comment]
I've been using the Vorkath plugin for a few trips now and it's pretty convenient to not get caught off guard. One thing I found is that the counter overlay is rather small and blends in with the environment so I struggle read it sometimes.

**Comment by runeliteplusplus** [comment]
What would you suggest for that? The best thing I can come up with is an option to bold the font and change color in config, would that be suitable?

**Comment by ghost** [comment]
Some custom graphics overlay similar to the demonic gorillas plugin would be nice but I think that's asking too much. Making the font more distinctive and easily legible would be sufficient.

**Comment by ghost** [comment]
1 other suggestion I would make is to highlight the 3x3 affected tiles for the bomb attack.

**Comment by trini0n** [comment]
Wouldn't that require that the old Projectile API files be brought back? I recall that Runelite removed the API for Projectile.getInteracting() due to abuse from other clients. 

If it is possible though I'd like to see if you could get the old AoE Indicators plugin working again? Let me know if you need the old AoE plugin files.

**Comment by runeliteplusplus** [comment]
Regarding the bomb attack, it is already somewhat inaccurate because if you are moving when it is thrown the tile is generally 1 square off.

I'm calculating where it lands based on Vorkath animation and the players location when the animation occurs.

I've tried highlighting a 3x3 area by modifying x and y values in the LocalPoint variable, however it does not seem to follow a 1:1 ratio, I'm not sure how a LocalPoint is obtained so I'm not sure how to calculate adjacent tiles from one.

For example modifying x and y values by 1 still highlights the same tile, even though the value is different.

Any insights into this and I will make a 3x3 highlight.

**Comment by trini0n** [comment]
IIRC the dev tool for Show Valid Movement draws a 3x3 tile around your character location, s o it may be worth looking at the code there. Sorry on mobile right now but maybe here?
https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/devtools/SceneOverlay.java

**Comment by runeliteplusplus** [comment]
I've updated the vorkath plugin, by default indicator text is now yellow and bold, much easier to read, with config options added.

It also highlight's a 3x3 area for the fireball attack now, many thanks trini0n.

Please if anyone can confirm what data is or isn't available from Alchemical Hydra I would greatly appreciate it.

**Comment by Matt5432** [comment]
It’s not available , I tried to get it too and couldn’t no idea why that is. Could you upload the hydra plugin you made. Does it tell you what to pray when they attack based off the animation? Would be nice if it did as then it could be expanded to a lot of other npcs

**Comment by Matt5432** [comment]
Facepalm just read your post ignore the pray but, sorry about that bit.

**Comment by ghost** [comment]
Could the font of the Quickfire Barrage counter during Poison Pool phase also be made bigger and bold
?

**Comment by ghost** [comment]
I like the 3x3 highlight but thought other people may prefer something else or use their own tile markers so perhaps there could be config option to turn highlight off, highlight 1 tile or 3x3.

**Comment by Matt5432** [comment]
@runeliteplusplus Do you have discord?

**Comment by runeliteplusplus** [comment]
I've just pushed a quick update as I haven't had much time to work on this recently,

Vorkath bold setting now also adjusts quickfire barrage counter.

Hydra plugin is out, would text color config be necessary here?

Will add Vorkath tile highlight functionality soon, keep the suggestions coming you guys.

**Comment by Matt5432** [comment]
@runeliteplusplus Possible for the hydra plugin to use the same system as the jad prayer flick with a box in corner with what to pray rather than text?
Tried to copy the plugin to make it work for another npc e.g. Waterfiends as they use range and mage but couldn't any help :S

**Comment by runeliteplusplus** [comment]
The Hydra plugin has been updated to use the same system as the jad pray flick box. I can see how a demonic gorilla type overlay would be the most useful here, but I've never messed around with that so I won't be implementing it, at least at this time.

Config option has been added to Vorkath where you can specify to highlight one tile, 3x3, or none for the fireball attack.

**Comment by IPlayScape** [comment]
Is this possible, so instead of a hydra plugin. an animation plugin that doesn't require an npc but if in combat and npc does that animation then it shows protect from melee, range or mage. Then instead of making a plugin for each npc , just add the animation ID to a list. Just like Matt said would be nice to have a stripped down one without timers above head just what to pray so I could learn off :) Just idea's don't want to sound like a leach :D

**Comment by ghost** [comment]
Really appreciate the fast updates.

**Comment by runeliteplusplus** [comment]
What other NPC's switch attack styles and can benefit from this sort of plugin?

**Comment by IPlayScape** [comment]
@runeliteplusplus My idea was if I could get the jad prayer icon in the corner , then add to Waterfiends , then was going to make for gwd1 bosses etc . with all the counters the code just through me off . Still learning alot at the moment. And for Vorkath maybe a message on screen when it does the purple attack to drop prayer? Just an idea :)
And as @AverageHumanoid really appreciate the fast responses!
