### ISSUE TITLE
Plugin Request(s) ?

### ISSUE THREAD

**Issue by DoughBoiKush** [runeliteplusplus/RuneLitePlusPlus#8]
Any plans of Infernal Cape plugin in the near future? Is there a DIscord for RL++ ?

Chambers of Xeric?
Raid Scouting Plugin?
Theatre of Blood?

Just thought i'd ask what features are being worked on, if any.

**Comment by runeliteplusplus** [comment]
Hello,

There is no discord.

I've been considering inferno / raids, the main problem being I've never done either activity so I don't know what a plugin would need to accomplish. If anyone wants to provide a detailed list of what a plugin should do, I can definitely take a closer look.

The second problem being runelite patches. They've already patched freeze timers by restricting access to graphic / animation data on players. I'm worried by making public a plugin to ezscape these activities would put a spotlight on RL++ and have all it's good plugins restricted / handicapped in some way.
